services:
  ingress:
    image: devorai/owallet-node-balancer:v1.1.5
    working_dir: /workspace
    restart: on-failure
    tty: true
    ports:
      - 80:80    
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
