init_worker_by_lua_block {
    local resty_roundrobin = require "resty.roundrobin"
    local rr_up = resty_roundrobin:new({
        ["10.108.0.5"] = 70,
        ["10.108.0.2"] = 5,
        ["10.108.0.3"] = 70
    })
    package.loaded.delay = 5  -- in seconds as block time
    package.loaded.rr_up = rr_up

    local function check(premature)
         if not premature then
             -- do the health check or other routine work
             local ok, err = ngx.timer.at(package.loaded.delay, check)
             if not ok then
                 ngx.log(ngx.ERR, "failed to create timer: ", err)
                 return
             end
         end
        rr_up:update()
    end

    local hdl, err = ngx.timer.at(0, check)
    if not hdl then
         ngx.log(ngx.ERR, "failed to create timer: ", err)
         return
    end

}

upstream rpc_rr {
    server 0.0.0.1;
    balancer_by_lua_block {
        local balancer = require "ngx.balancer"
        balancer.set_current_peer(package.loaded.rr_up:next(), 26657)
        balancer.set_more_tries(3)
    }
}

server {
    listen 80;
    server_name usa.rpc.orai.io;

    set $template_root /var/www/templates;

    location ~* ^/(genesis|genesis_chunked|block_search|tx_search)(.*) {
        deny all;
        return 403;
    }
    location / {
        proxy_pass http://rpc_rr;
        add_header  X-Upstream  $upstream_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
    location /_weight/ {
        root html;
        default_type 'text/html';
        content_by_lua_block {
            local template = require "resty.template"
            local local_rr_up = package.loaded.rr_up
            template.render("view.html", {
                gcd = local_rr_up.gcd,
                heights = local_rr_up.heights,
                nodes = local_rr_up.nodes,
                max_height = local_rr_up:get_max_height(),
                interval = package.loaded.delay,
                link = "https://scan.orai.io",
            })
        }
    }
    location = /favicon.ico {
        return 301 https://scan.orai.io/favicon.ico;
    }
}

upstream aglbk {
  server 10.108.0.4:4001;
  server 65.109.74.254:4001 backup;
}

server {
  listen 80;
  server_name backend.agents.land;
  location / {
    add_header  X-Upstream  $upstream_addr;
    proxy_pass http://aglbk;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    add_header X-Server DO;
  }
}

upstream solana-rpc-endpoints-new {
    keepalive 32;
    server 127.0.0.1:8071;
    server 127.0.0.1:8072;
}

server {
    listen 8071;
    location / {
        proxy_pass https://mainnet.helius-rpc.com/?api-key=a29ce73b-800f-4598-a121-51043999cde2;
        proxy_ssl_server_name on;
        proxy_ssl_session_reuse on;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}

server {
    listen 8072;
    location / {
        proxy_pass https://mainnet.helius-rpc.com/?api-key=3b28a0fc-0ef6-48ef-b55c-c55ae74cb6a6;
        proxy_ssl_server_name on;
        proxy_ssl_session_reuse on;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}

server {
    listen 80;
    server_name solana-public-do.agents.land;
    location / {
        #proxy_pass https://mainnet.helius-rpc.com/?api-key=a29ce73b-800f-4598-a121-51043999cde2;
        #proxy_ssl_server_name on;
        proxy_pass http://solana-rpc-endpoints-new;
        #add_header "X-Upstream" $upstream_addr;
    }
}
